apiVersion: apps/v1
kind: Deployment
metadata:
  name: helpdesk
spec:
  selector:
    matchLabels:
      app: helpdesk
  template:
    metadata:
      labels:
        app: helpdesk
    spec:
      containers:
      - name: helpdesk
        image: talissonmelo/helpdesk:latest
