apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replic-set-helpdesk
spec:
  replicas: 3
  selector:
    matchLabels:
      app: helpdesk
  template:
    metadata:
      labels:
        app: helpdesk
    spec:
      containers:
        - name: helpdesk
          image: talissonmelo/helpdesk:latest

