apiVersion: apps/v1
kind: Deployment
metadata:
  name: anime-deployment
spec:
  selector:
    matchLabels:
      app: anime
  template:
    metadata:
      labels:
        app: anime
    spec:
      containers:
      - name: anime
        image: talissonmelo/anime:latest
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: conf-anime
