apiVersion: apps/v1
kind: Deployment
metadata:
  name: anime-deployment
spec:
  selector:
    matchLabels:
      app: anime
  template:
    metadata:
      labels:
        app: anime
    spec:
      containers:
      - name: anime
        image: talissonmelo/anime:latest
        resources:
          requests:
            memory: "256Mi"
            cpu: "400m"
          limits:
            memory: "512Mi"
            cpu: "1000m"
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /escolas/nomes?nome=Pro
            port: 8080
            scheme: HTTP
          successThreshold: 5  
          initialDelaySeconds: 60
        startupProbe:
          httpGet:
            path: /escolas
            port: 8080
            scheme: HTTP
          failureThreshold: 30
          periodSeconds: 10
          initialDelaySeconds: 60
        livenessProbe:
          httpGet:
            path: /escolas
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
        envFrom:
          - secretRef:
              name: secret-anime
